name             'git'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures git'
long_description 'Installs/Configures git'
version          '0.1.0'
