name             'cakephp'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cakephp'
long_description 'Installs/Configures cakephp'
version          '0.1.0'
