name             'php'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures php'
long_description 'Installs/Configures php'
version          '0.1.0'
