source "https://supermarket.chef.io"
cookbook "vim",       path: "site-cookbooks/vim"
cookbook "git",       path: "site-cookbooks/git"
cookbook "remi",      path: "site-cookbooks/remi"
cookbook "apache",    path: "site-cookbooks/apache"
cookbook "firewalld", path: "site-cookbooks/firewalld"
cookbook "php",       path: "site-cookbooks/php"
cookbook "mysql",     path: "site-cookbooks/mysql"
cookbook "composer",  path: "site-cookbooks/composer"
cookbook "cakephp",   path: "site-cookbooks/cakephp"
cookbook "nodejs",    path: "site-cookbooks/nodejs"
#cookbook "hello",     path: "site-cookbooks/hello"
#cookbook "resources", path: "site-cookbooks/resources"
#cookbook 'mysql', '~> 6.0.0'
