name             'localdef'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures localdef'
long_description 'Installs/Configures localdef'
version          '0.1.0'
