name             'firewalld'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures firewalld'
long_description 'Installs/Configures firewalld'
version          '0.1.0'
