name             'hello'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures hello'
long_description 'Installs/Configures hello'
version          '0.1.0'
