name             'remi'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures remi'
long_description 'Installs/Configures remi'
version          '0.1.0'
